configfile: "config/config.yaml"


def get_factor_list():
    import pandas as pd

    df = pd.read_csv(config["metadata"])
    factor_list = df.query("TrackClass == 'TFs and others'")["TrackType"].unique()
    return factor_list


factor_list = get_factor_list()


include: "rules/prepare_data.smk"
include: "rules/motif_scan.smk"
include: "rules/generate.smk"
include: "rules/network.smk"


rule all:
    input:
        config["results_dir"] + "network/enrichment_analysis.csv",
