configfile: "config/config.yaml"


with open(config["factor_list"]) as f:
    factor_list = [line.strip() for line in f.readlines()]

with open(config["query_set"]) as f:
    query_set = [line.strip() for line in f.readlines()]


include: "rules/prepare_data.smk"
include: "rules/generate.smk"
include: "rules/motif_scan.smk"
include: "rules/network.smk"
include: "rules/tf_activities.smk"


rule all:
    input:
        expand(
            config["results_dir"] + "data/{threshold}/distances.parquet",
            threshold=config["thresholds"],
        ),
        config["results_dir"] + "tf_activities/results.parquet",
