downloads_dir: "/home/brandon/data/chip_atlas/"
results_dir: "results/"

metadata: "resources/metadata.csv"
query_ids:
  - SRX7071213
  - SRX7071214
  - SRX7071215
  - SRX7071216
  - SRX7071217
  - SRX7071218

motif_scan:
  motif_dbs:
    - CIS-BP
  factors:
    - JUN
    - JUNB
    - JUND
    - FOS
    - FOSB

tfsage:
  n: 15

linkages:
  - cellranger-arc
  - rp-grn

decoupler_networks:
  - dorothea
  - collectri

deseq2_results: "data/GSE128242_deseq2.csv"

thresholds: ["10", "20"]
