results_dir: "results/"
chip_metadata: "resources/metadata.csv"
factor_list: "resources/factor_list.txt"
query_set: "resources/query_set.txt"

thresholds: ["05", "10", "20"]
holdout_factors: ["JUN", "MED12"]
tfsage_n: [15]
motif_dbs:
  - HOCOMOCOv11_HUMAN
  - CIS-BP