results_dir: "results/"
chip_metadata: "resources/metadata.csv"
factor_list: "resources/factor_list.txt"
query_set: "resources/query_set.txt"
benchmark_set: "resources/benchmark_set.csv"

thresholds: ["05", "10", "20"]
tfsage_n: [15]
motif_dbs:
  - CIS-BP

network:
  score_threshold_q: 0.85
  
curated_dbs:
  - dorothea
  - collectri